### ISSUE TITLE
Experience bottler won't drop when broken

### ISSUE THREAD

**Issue by mastery3** [eideehi/mc-experiencebottler#1]
^

**Comment by eideehi** [comment]
Oops, I did it. I'll fix it.

**Comment by mastery3** [comment]
Also this mod is severely underrated :P

**Comment by eideehi** [comment]
Thanks for thinking so highly of Experience Bottler! I often have a bad habit of skipping mod updates, but I'll do my best to keep it up to date.

Thank you for reporting the bug. I hope you will continue to report bugs as you find them.
