### ISSUE TITLE
[Failed ot start the Server] Could not execute entrypoint stage 'main' due to errors, provided by 'experiencebottler'!

### ISSUE THREAD

**Issue by SpigotDE** [eideehi/mc-experiencebottler#11]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Mod version

1.19+build.2

### Is this a bug caused by this mod alone?

The bug was reproduced with this mod alone

### What happened?

I tried to start the dedicated server for our Aged Modpack.

Maybe the log helps you out

Fabric 1.19.2

PS:
I havent tried the mod alone

### Steps to reproduce the bug

Only crashes on dedicated server

### Logs and screenshots

https://gist.github.com/SpigotDE/3d5fa3bd59a688d065a76b9f5da38881

**Comment by SpigotDE** [comment]
Without the mod, the server starts as usual

**Comment by eideehi** [comment]
I have confirmed that the server does not start. Please use version 1.19+build.1 which does not have this issue. You can use it without any problems as long as there are no players with abnormal amounts of experience points. The supported versions listed on the distribution site will be revised later.
