### ISSUE TITLE
crash when leaving singleplayer world

### ISSUE THREAD

**Issue by someonedeepintheinternet** [eideehi/mc-experiencebottler#13]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Mod version

1.20.1+build.1

### Is this a bug caused by this mod alone?

The bug was reproduced with this mod alone

### List of mods to reproduce bug

[modlist.txt](https://github.com/eideehi/mc-experiencebottler/files/12446952/modlist.txt)

### What happened?

when leaving my Single Player world it crashes Minecraft. I may have a few mods but I assure you it crashes only when I used your mod, doesn't mean the sole mod itself causes the issue(which is why I'm unsure with the "is this bug caused by this mod alone" option). I'm too dumb to read logs or figure out conflicts between mods.

Crash Report:
[crash-2023-08-27_01.50.53-client.txt](https://github.com/eideehi/mc-experiencebottler/files/12446957/crash-2023-08-27_01.50.53-client.txt)

### Steps to reproduce the bug

1. open options
2. click button "Save and Quit to Title"
3. crash

### Logs and screenshots

[latest.log](https://github.com/eideehi/mc-experiencebottler/files/12446954/latest.log)
[debug.log](https://github.com/eideehi/mc-experiencebottler/files/12446956/debug.log)

**Comment by eideehi** [comment]
Thank you for your report. This bug has been resolved in version 1.20.1+build.2.

The issue stemmed from an assumption that the item initialization process would only be called once. Even without other mods installed, the bug can be reproduced in Creative Mode by opening the inventory, returning to the title screen, loading the game again, and then opening the inventory once more.
