### ISSUE TITLE
Necessary files required to compile the mod are missing 

### ISSUE THREAD

**Issue by mastery3** [eideehi/mc-experiencebottler#5]
./gradlew and ./gradlew.bat are missing

**Comment by mastery3** [comment]
Even with these files, it still fails to compile because of a GradleWrapper error saying something is missing

**Comment by eideehi** [comment]
Oops, I haven't used the Gradle Wrapper for a long time now, so I didn't even notice that the file was missing. I'll add it.

**Comment by mastery3** [comment]
You use gradle directly?

**Comment by eideehi** [comment]
I use Intellij IDEA, which allows me to run Gradle commands in GUI, so I am less aware of the Wrapper.
